[[plugins]]
repo = 'scrooloose/syntastic'
on_ft = ['python']
hook_add = '''
  let g:syntastic_python_checkers = ['pydocstyle', 'pycodestyle', 'pyflakes']
'''

[[plugins]]
repo = 'maxmellon/vim-jsx-pretty'
on_ft = ['javascript', 'typescriptreact', 'typescript', 'javascriptreact']
